version: "3.3"
services:
  tree_server:
    image: "whobrokethebuild/mdsplus:tree-server"
    environment:
      - "demo_path=/trees/~t/"
      - "arduino_path=/trees/~t/"
      - "UID=${UID}"
      - "GID=${GID}"
    volumes:
      - ./trees:/trees
      - ./pydevices:/pydevices
    ports:
      - "8000:8000"
  dispatch_server:
    image: "whobrokethebuild/mdsplus:dispatch-server"
    env_file:
      - trees.env
    environment:
      - "UID=${UID}"
      - "GID=${GID}"
    ports:
      - "8100:8100"
  daq_server:
    image: "whobrokethebuild/mdsplus:daq-server"
    env_file:
      - trees.env
    environment:
      - "UID=${UID}"
      - "GID=${GID}"
    ports:
      - "8200:8200"