version: "3.3"
services:
  tree_server:
    image: "whobrokethebuild/mdsplus:tree-server"
    environment:
      - "demo_path=/trees/~t/"
      - "arduino_path=/trees/~t/"
      - "UID=${UID}"
      - "GID=${GID}"
    volumes:
      - ./trees:/trees
      - ./pydevices:/pydevices
      - ./scripts:/scripts
    ports:
      - "8000:8000"
  dispatch_server:
    image: "whobrokethebuild/mdsplus:mdsip-server"
    env_file:
      - trees.env
      - servers.env
    environment:
      - "MDSIP_PORT=8101"
      - "UID=${UID}"
      - "GID=${GID}"
    volumes:
      - ./pydevices:/pydevices
      - ./scripts:/scripts
    ports:
      - "8101:8101"
  daq_server:
    image: "whobrokethebuild/mdsplus:mdsip-server"
    env_file:
      - trees.env
      - servers.env
    environment:
      - "MDSIP_PORT=8102"
      - "UID=${UID}"
      - "GID=${GID}"
    volumes:
      - ./pydevices:/pydevices
      - ./scripts:/scripts
    ports:
      - "8102:8102"
  analysis_server:
    image: "whobrokethebuild/mdsplus:mdsip-server"
    env_file:
      - trees.env
      - servers.env
    environment:
      - "MDSIP_PORT=8103"
      - "UID=${UID}"
      - "GID=${GID}"
    volumes:
      - ./pydevices:/pydevices
      - ./scripts:/scripts
    ports:
      - "8103:8103"